### ISSUE TITLE
Add release system

### ISSUE THREAD

**Issue by amalv** [amalv/contract-api#1]
### Objective
Add a release system to the contract-api repository using the release-please GitHub Action.

### Steps to Follow
1. **Configure GitHub Actions**:
   - Create a new workflow file at `.github/workflows/release-please.yml` with the following content:

     ```yaml
     on:
       push:
         branches:
           - main

     permissions:
       contents: write
       pull-requests: write

     name: release-please

     jobs:
       release-please:
         runs-on: ubuntu-latest
         steps:
           - uses: actions/checkout@v4
           - uses: googleapis/release-please-action@v4
             with:
               token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
               release-type: simple
     ```

### Follow-up Steps
1. **Create a Personal Access Token (PAT)**:
   - Create a PAT with the following permissions:
     - `repo` (Full control of private repositories)
     - `workflow` (Update GitHub Action workflows)
     - `write:packages` (Upload packages to GitHub)
   - Configure the PAT as a GitHub action secret named `MY_RELEASE_PLEASE_TOKEN`.

2. **Make conventional commits**:
   - Make some conventional commits and push changes to the main branch to test the setup.

3. **Update the README.md**:
   - Document the release process for contributors.

### Testing
- Make a commit with the message `feat: add release system` and push it to the main branch.
- Verify that the release system creates releases as expected.
- Ensure that all steps are documented for future references.
